<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TintaESReader</AssemblyName>
    <RootNamespace>TintaES.Reader</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TintaES.Wpf\TintaES.Wpf.csproj" />
  </ItemGroup>
</Project>
