<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TintaES</AssemblyName>
    <RootNamespace>TintaES.Wpf</RootNamespace>
    <ApplicationIcon />
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TintaES.Core\TintaES.Core.csproj" />
    <Resource Include="..\..\engine\manga-image-translator\fonts\anime_ace_3.ttf"
              Link="Resources\Fonts\anime_ace_3.ttf" />
  </ItemGroup>
</Project>
